<a href="https://colab.research.google.com/github/foresterprakash/basic/blob/main/Numpy_prakash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data science in Numpy.
Numpy fundamentals 
Following fundamental concepts and methods are essential to learn Numpy in Python language

*   Array creation
*Indexing on ndarrays
*I/O with NumPy
*Data types
*Broadcasting
*Copies and views
*Structured arrays
*Universal functions (ufunc) basics


[Numpy basics](https://numpy.org/devdocs/user/basics.html)




## 1 . Array creation
There are 6 general mechanisms for creating arrays:

* Conversion from other Python structures (i.e. lists and tuples)

* Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

* Replicating, joining, or mutating existing arrays

You can use these methods to create ndarrays or Structured arrays. This document will cover general methods for ndarray creation.

## 1.1 Conversion from python structures (list and tuples)

In [14]:
# converting the python structures ( i.e. Lists and tuples)
# NumPy arrays can be defined using Python sequences such as lists and tuples. Lists and tuples are defined using [...] and (...), respectively. Lists and tuples can define ndarray creation:
# a list of numbers will create a 1D array,
# a list of lists will create a 2D array,
# further nested lists will create higher-dimensional arrays. In general, any array object is called an ndarray in NumPy.
# Creating python lists of multidimensions
l1 = [2,4,6,8,10]
l2 = [[1,3,5],[7,9,11]]
l3 = [[1,2,3],[4,5,6],[7,8,9]]

In [15]:
# Lets import the numpy in the note book.
# To install numpy 
# pip install numpy
import numpy as np

In [16]:
# Convert array from th python list in numpy
a1D = np.array(l1) # one dimensional array
a1D

array([ 2,  4,  6,  8, 10])

In [25]:
a1D.ndim

1

In [17]:
a2D = np.array(l2) # two dimensional array
a2D

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [26]:
a2D.ndim

2

In [18]:
a3D = np.array(l3) # three dimensional array
a3D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
a2D.ndim

2

In [28]:
a2D.dtype

dtype('int64')

In [19]:
# Create a python tuples and convert into array

In [20]:
t1 = (1,2,3,4,5)

In [22]:
at = np.array(t1)


In [23]:
at

array([1, 2, 3, 4, 5])

In [24]:
at.ndim

1

In [29]:
at.dtype

dtype('int64')

## 1.2 Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

In [30]:
# creating 1D array
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
#with mentioning data type
np.arange(1,10,dtype = float)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [36]:
# With mentioning the or interval
np.arange(1,4,0.5,dtype = float)

array([1. , 1.5, 2. , 2.5, 3. , 3.5])

In [39]:
# with linespace - creates the fix interval between the range
np.linspace(1.,10.,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [41]:
# creating 2D array
# Multidimensional array are the vectors
# functions are np.eye, np.diag and np.vander
np.eye(3) # it creates the unit square matrix of 3 rows and columns

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
np.eye(2,3) # creates the matrix with 2 rows and 3 columns

array([[1., 0., 0.],
       [0., 1., 0.]])

In [44]:
np.diag([1,2,3]) # This creates the matrix with digonal value 1,2 and 3

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [49]:
np.vander(np.linspace(1,10,5),2)

array([[ 1.  ,  1.  ],
       [ 3.25,  1.  ],
       [ 5.5 ,  1.  ],
       [ 7.75,  1.  ],
       [10.  ,  1.  ]])

In [52]:
np.vander((1,2),2)

array([[1, 1],
       [2, 1]])

In [53]:
np.vander((1,2,3,4),5)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1]])

[Details on Vandermonde matrix](https://mathworld.wolfram.com/VandermondeMatrix.html#:~:text=A%20Vandermonde%20matrix%20is%20a,83)

### General array creating functions
The ndarray creation functions e.g. numpy.ones, numpy.zeros, and random define arrays based upon the desired shape. The ndarray creation functions can create arrays with any dimension by specifying how many dimensions and length along that dimension in a tuple or list.

**np.zeros** 

In [56]:
np.zeros((2,3)) # creates the 2 *3 vector of value o

array([[0., 0., 0.],
       [0., 0., 0.]])

In [60]:
np.zeros((2,3,2)) # creates the 3 dimensional array with value 0

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

**np.ones**

In [61]:
np.ones((2,3)) # same as np.zeros but the value will be 1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [62]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

**random**

In [64]:
import random
random.seed(40)
data = [random.randint(1, 10) for i in range(10)]
data

[8, 10, 9, 1, 4, 5, 4, 3, 6, 5]

In [66]:
np.array(data)

array([ 8, 10,  9,  1,  4,  5,  4,  3,  6,  5])

### 1.3 Replicating, joining, or mutating existing arrays

Once you have created arrays, you can replicate, join, or mutate those existing arrays to create new arrays. When you assign an array or its elements to a new variable, you have to explicitly numpy.copy

In [70]:
a = np.array([1,2,3,4,5]) # creating an array
b = a[:2] # slicing array upto index 2
b += 1 # adding 1 to the array b
print('a',a, ';b', b) # this gives two array one is original a and another is b

a [2 3 3 4 5] ;b [2 3]


Now using copy function but same result

In [73]:
a = np.array([1, 2, 3, 4])
b = a[:2].copy()
b += 1
print('a = ', a, ';b = ', b)

a =  [1 2 3 4] ;b =  [2 3]


# 2. Indexing on ndarrays

ndarrays can be indexed using the standard Python x[obj] syntax, where x is the array and obj the selection. There are different kinds of indexing available depending on obj: basic indexing, advanced indexing and field access.

Most of the following examples show the use of indexing when referencing data in an array. The examples work just as well when assigning to an array. See Assigning values to indexed arrays for specific examples and explanations on how assignments work.

Note that in Python, x[(exp1, exp2, ..., expN)] is equivalent to x[exp1, exp2, ..., expN]; the latter is just syntactic sugar for the former.

### 2.1 Basic : single element indexing

In [76]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
x[2] # Gives the result 2
# This is the forward indexing which starts with 0 to n i.e., 
# If you want to return 3rd value then indexing will be 2 (0,1,2)

2

In [80]:
x[-2] # gives the result 8
# This is the backward indexing which starts with -1,-2,....n i.e.,
# If you want to return last value then then use the index as -1

8

In [83]:
x.shape = (2,5) # it converts the x into 2 dimensions ( 2 rows and 5 columns)
# Now indexing should mention both row and column

In [84]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [87]:
x[1,3] # It shows the value of second row and forth column = 8

8